/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-16 at 18:29:04 UTC 
 * Modify at your own risk.
 */

package com.google.cloud.backend.android.mobilebackend.model;

/**
 * Model definition for BlobAccess.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the mobilebackend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BlobAccess extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String accessUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mandatoryHeaders;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shortLivedUrl;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccessUrl() {
    return accessUrl;
  }

  /**
   * @param accessUrl accessUrl or {@code null} for none
   */
  public BlobAccess setAccessUrl(java.lang.String accessUrl) {
    this.accessUrl = accessUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMandatoryHeaders() {
    return mandatoryHeaders;
  }

  /**
   * @param mandatoryHeaders mandatoryHeaders or {@code null} for none
   */
  public BlobAccess setMandatoryHeaders(java.lang.String mandatoryHeaders) {
    this.mandatoryHeaders = mandatoryHeaders;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShortLivedUrl() {
    return shortLivedUrl;
  }

  /**
   * @param shortLivedUrl shortLivedUrl or {@code null} for none
   */
  public BlobAccess setShortLivedUrl(java.lang.String shortLivedUrl) {
    this.shortLivedUrl = shortLivedUrl;
    return this;
  }

  @Override
  public BlobAccess set(String fieldName, Object value) {
    return (BlobAccess) super.set(fieldName, value);
  }

  @Override
  public BlobAccess clone() {
    return (BlobAccess) super.clone();
  }

}
