/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-03-20 15:12:36 UTC)
 * on 2013-03-28 at 05:39:01 UTC
 * Modify at your own risk.
 */

package com.google.cloud.backend.android.mobilebackend.model;

/**
 * Model definition for FilterDto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 */
@SuppressWarnings("javadoc")
public final class FilterDto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Filter datastoreFilter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<FilterDto> subfilters;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Object> values;

  /**
   * @return value or {@code null} for none
   */
  public Filter getDatastoreFilter() {
    return datastoreFilter;
  }

  /**
   * @param datastoreFilter datastoreFilter or {@code null} for none
   */
  public FilterDto setDatastoreFilter(Filter datastoreFilter) {
    this.datastoreFilter = datastoreFilter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperator() {
    return operator;
  }

  /**
   * @param operator operator or {@code null} for none
   */
  public FilterDto setOperator(java.lang.String operator) {
    this.operator = operator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<FilterDto> getSubfilters() {
    return subfilters;
  }

  /**
   * @param subfilters subfilters or {@code null} for none
   */
  public FilterDto setSubfilters(java.util.List<FilterDto> subfilters) {
    this.subfilters = subfilters;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Object> getValues() {
    return values;
  }

  /**
   * @param values values or {@code null} for none
   */
  public FilterDto setValues(java.util.List<java.lang.Object> values) {
    this.values = values;
    return this;
  }

  @Override
  public FilterDto set(String fieldName, Object value) {
    return (FilterDto) super.set(fieldName, value);
  }

  @Override
  public FilterDto clone() {
    return (FilterDto) super.clone();
  }

}
